[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

function Read-Default([string]$Prompt, [string]$Default) {
  $value = Read-Host "$Prompt [$Default]"
  if ([string]::IsNullOrWhiteSpace($value)) {
    return $Default
  }
  return $value.Trim()
}

function Read-YesNo([string]$Prompt, [bool]$Default = $true) {
  $defaultText = if ($Default) { 'Y/n' } else { 'y/N' }
  $value = Read-Host "$Prompt [$defaultText]"
  if ([string]::IsNullOrWhiteSpace($value)) {
    return $Default
  }
  return $value.Trim().ToLowerInvariant() -in @('y', 'yes', '是')
}

function Read-EnvValue([string]$Path, [string]$Name, [string]$Default) {
  if (-not (Test-Path -LiteralPath $Path)) {
    return $Default
  }

  $line = Get-Content -LiteralPath $Path | Where-Object {
    $_ -match "^\s*$([regex]::Escape($Name))\s*="
  } | Select-Object -First 1

  if (-not $line) {
    return $Default
  }
  $value = ($line -split '=', 2)[1].Trim().Trim('"', "'")
  if ([string]::IsNullOrWhiteSpace($value)) {
    return $Default
  }
  return $value
}

$projectRoot = Split-Path -Parent $PSScriptRoot
$envFile = Join-Path $projectRoot '.env'
$startScript = Join-Path $PSScriptRoot 'start-hidden.ps1'
$startupScript = Join-Path $PSScriptRoot 'install-startup.ps1'

Write-Host ''
Write-Host '==============================================' -ForegroundColor Cyan
Write-Host ' AgentRouter 兼容代理：一键配置' -ForegroundColor Cyan
Write-Host '==============================================' -ForegroundColor Cyan
Write-Host '此向导只配置本地代理地址和行为。'
Write-Host 'OpenCode / Cherry Studio 继续在各自的界面中填写原本的 API Key。'
Write-Host ''

if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
  throw '找不到 Node.js。请安装 Node.js 20 或更高版本，然后再次运行此脚本。'
}

$existingBaseUrl = Read-EnvValue $envFile 'UPSTREAM_BASE_URL' 'https://agentrouter.org/v1'
$existingPort = Read-EnvValue $envFile 'PORT' '8787'

do {
  $upstreamBaseUrl = Read-Default 'AgentRouter API 地址' $existingBaseUrl
  try {
    $uri = [uri]$upstreamBaseUrl
    $validUrl = $uri.Scheme -in @('http', 'https') -and -not [string]::IsNullOrWhiteSpace($uri.Host)
  } catch {
    $validUrl = $false
  }
  if (-not $validUrl) {
    Write-Host '地址无效，请输入完整 http(s) URL，例如 https://agentrouter.org/v1。' -ForegroundColor Red
  }
} until ($validUrl)

do {
  $port = Read-Default '本地代理端口' $existingPort
  $validPort = 0
  $parsedPort = 0
  $validPort = [int]::TryParse($port, [ref]$parsedPort) -and $parsedPort -ge 1 -and $parsedPort -le 65535
  if (-not $validPort) {
    Write-Host '端口必须是 1 到 65535 的整数。' -ForegroundColor Red
  }
} until ($validPort)

$enableStartup = Read-YesNo '登录 Windows 后自动启动代理？' $true

$envContent = @(
  '# Generated by scripts/setup.ps1. Safe to edit manually.',
  'HOST=127.0.0.1',
  "PORT=$parsedPort",
  "UPSTREAM_BASE_URL=$($upstreamBaseUrl.TrimEnd('/'))",
  'CHERRY_USE_OPENCODE_PROFILE=true',
  'CLIENT_HEADER_PROFILE_FILE=.client-header-profile.json',
  'DROP_BILLING_SSE=true',
  'LOG_LEVEL=info',
  ''
)
Set-Content -LiteralPath $envFile -Value $envContent -Encoding utf8
Write-Host ''
Write-Host "已写入配置：$envFile" -ForegroundColor Green

if ($enableStartup) {
  & $startupScript -Force
}

Write-Host ''
Write-Host '下一步（只需一次）：' -ForegroundColor Yellow
Write-Host "1. OpenCode 的 Base URL 填：http://127.0.0.1:$parsedPort/v1"
Write-Host "2. Cherry Studio 的 API 地址填：http://127.0.0.1:$parsedPort"
Write-Host '3. 两个客户端各自继续使用原来的 API Key。'
Write-Host '4. Cherry Studio 可以直接使用，不需要安装或运行 OpenCode。'
Write-Host ''

if (Read-YesNo '现在启动代理？' $true) {
  & $startScript
}
